#!/usr/bin/env python3
"""Generate deterministic Phase A C layout and reflection artifacts."""
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path

SCALARS = {"u8": (1, 1), "u16": (2, 2), "u32": (4, 4), "u64": (8, 8),
           "i32": (4, 4), "i64": (8, 8), "f32": (4, 4), "f64": (8, 8),
           "ptr": (8, 8), "capability": (8, 8)}

def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))

def align_up(value, alignment):
    return (value + alignment - 1) // alignment * alignment

def layout(schema):
    types = schema["types"]
    cache = {}
    def one(name):
        if name in cache: return cache[name]
        desc = types[name]
        if desc["kind"] != "struct": raise ValueError(f"unsupported type kind: {name}")
        offset, max_align, fields = 0, 1, []
        for field in desc["fields"]:
            typ = field["type"]
            size, alignment = SCALARS.get(typ, (None, None))
            if size is None:
                nested = one(typ); size, alignment = nested["size"], nested["align"]
            count = int(field.get("array", 1))
            offset = align_up(offset, alignment)
            fields.append({"name": field["name"], "type": typ, "offset": offset,
                           "size": size * count, "alignment": alignment, "array": count})
            offset += size * count; max_align = max(max_align, alignment)
        result = {"name": name, "size": align_up(offset, max_align), "align": max_align,
                  "fields": fields}
        cache[name] = result; return result
    return {name: one(name) for name in types}

def c_type(typ):
    return {"u8":"uint8_t", "u16":"uint16_t", "u32":"uint32_t", "u64":"uint64_t",
            "i32":"int32_t", "i64":"int64_t", "f32":"float", "f64":"double",
            "ptr":"uint64_t", "capability":"uint64_t"}.get(typ, f"VgSchema_{typ}")

def emit(schema, out_dir):
    raw = canonical(schema).encode("utf-8")
    schema_id = hashlib.sha256(raw).hexdigest()[:16]
    layouts = layout(schema)
    root = schema["root"]
    stem = re.sub(r"[^A-Za-z0-9]+", "_", schema["name"]).lower()
    guard = f"VG_GENERATED_{stem.upper()}_H"
    lines = [f"/* generated by vg-schema; source-sha256: {hashlib.sha256(raw).hexdigest()} */",
             "/* do not edit */", "#ifndef " + guard, "#define " + guard,
             "#include <stdint.h>", "#include <stddef.h>",
             "#ifdef __cplusplus",
             "#define VG_SCHEMA_STATIC_ASSERT(cond, msg) static_assert((cond), msg)",
             "#else",
             "#define VG_SCHEMA_STATIC_ASSERT(cond, msg) _Static_assert((cond), msg)",
             "#endif",
             f"#define VG_SCHEMA_{stem.upper()}_ID UINT64_C(0x{schema_id})"]
    for name, desc in layouts.items():
        lines.append(f"typedef struct VgSchema_{name} {{")
        for field in schema["types"][name]["fields"]:
            count = int(field.get("array", 1)); suffix = f"[{count}]" if count != 1 else ""
            lines.append(f"  {c_type(field['type'])} {field['name']}{suffix};")
        lines.append(f"}} VgSchema_{name};")
        lines.append(f"VG_SCHEMA_STATIC_ASSERT(sizeof(VgSchema_{name}) == {desc['size']}, \"schema size {name}\");")
        for field in desc["fields"]:
            lines.append(f"VG_SCHEMA_STATIC_ASSERT(offsetof(VgSchema_{name}, {field['name']}) == {field['offset']}, \"schema offset {name}.{field['name']}\");")
    lines += ["#undef VG_SCHEMA_STATIC_ASSERT", "#endif"]
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "vg_task_root.h").write_text("\n".join(lines) + "\n", encoding="utf-8")
    reflection = {"schema": schema["schema"], "name": schema["name"], "version": schema["version"],
                  "schema_id": "sha256:" + hashlib.sha256(raw).hexdigest(), "layouts": layouts, "source_hash": "sha256:" + hashlib.sha256(raw).hexdigest()}
    (out_dir / "vg_task_root.reflection.json").write_text(json.dumps(reflection, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / "vg_task_root.layout.json").write_text(json.dumps({"schema_id": reflection["schema_id"], "root": root, "layout": layouts[root]}, indent=2, sort_keys=True) + "\n", encoding="utf-8")

def main():
    parser = argparse.ArgumentParser(); parser.add_argument("schema"); parser.add_argument("--out-dir", required=True)
    args = parser.parse_args(); source = Path(args.schema); emit(json.loads(source.read_text(encoding="utf-8")), Path(args.out_dir))

if __name__ == "__main__": main()
