#!/usr/bin/env python3
"""Generate deterministic Phase A C layout and reflection artifacts."""
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path

SCALARS = {"u8": (1, 1), "u16": (2, 2), "u32": (4, 4), "u64": (8, 8),
           "i32": (4, 4), "i64": (8, 8), "f32": (4, 4), "f64": (8, 8),
           "ptr": (8, 8), "capability": (8, 8), "facet_ref": (8, 4)}

def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))

def align_up(value, alignment):
    return (value + alignment - 1) // alignment * alignment

def layout(schema):
    types = schema["types"]
    cache = {}
    def one(name):
        if name in cache: return cache[name]
        desc = types[name]
        if desc["kind"] != "struct": raise ValueError(f"unsupported type kind: {name}")
        offset, max_align, fields = 0, 1, []
        for field in desc["fields"]:
            typ = field["type"]
            size, alignment = SCALARS.get(typ, (None, None))
            if size is None:
                nested = one(typ); size, alignment = nested["size"], nested["align"]
            count = int(field.get("array", 1))
            offset = align_up(offset, alignment)
            fields.append({"name": field["name"], "type": typ, "offset": offset,
                           "size": size * count, "alignment": alignment, "array": count})
            offset += size * count; max_align = max(max_align, alignment)
        result = {"name": name, "size": align_up(offset, max_align), "align": max_align,
                  "fields": fields}
        cache[name] = result; return result
    return {name: one(name) for name in types}

def c_type(typ):
    return {"u8":"uint8_t", "u16":"uint16_t", "u32":"uint32_t", "u64":"uint64_t",
            "i32":"int32_t", "i64":"int64_t", "f32":"float", "f64":"double",
            "ptr":"uint64_t", "capability":"uint64_t", "facet_ref":"VgFacetRef"}.get(typ, f"VgSchema_{typ}")

def emit(schema, out_dir):
    raw = canonical(schema).encode("utf-8")
    schema_id = hashlib.sha256(raw).hexdigest()[:16]
    layouts = layout(schema)
    root = schema["root"]
    stem = re.sub(r"[^A-Za-z0-9]+", "_", schema["name"]).lower()
    guard = f"VG_GENERATED_{stem.upper()}_H"
    uses_facet_ref = any(field["type"] == "facet_ref"
                         for desc in schema["types"].values() for field in desc["fields"])
    lines = [f"/* generated by vg-schema; source-sha256: {hashlib.sha256(raw).hexdigest()} */",
             "/* do not edit */", "#ifndef " + guard, "#define " + guard,
             "#include <stdint.h>", "#include <stddef.h>"]
    if uses_facet_ref:
        lines.append("#include <vg/vg.h>")
    lines += [
             "#ifdef __cplusplus",
             "#define VG_SCHEMA_STATIC_ASSERT(cond, msg) static_assert((cond), msg)",
             "#else",
             "#define VG_SCHEMA_STATIC_ASSERT(cond, msg) _Static_assert((cond), msg)",
             "#endif",
             f"#define VG_SCHEMA_{stem.upper()}_ID UINT64_C(0x{schema_id})"]
    if "contract_name" in schema:
        lines.append(f"#define VG_SCHEMA_{stem.upper()}_CONTRACT_NAME \"{schema['contract_name']}\"")
    for name, desc in layouts.items():
        lines.append(f"typedef struct VgSchema_{name} {{")
        for field in schema["types"][name]["fields"]:
            count = int(field.get("array", 1)); suffix = f"[{count}]" if count != 1 else ""
            lines.append(f"  {c_type(field['type'])} {field['name']}{suffix};")
        lines.append(f"}} VgSchema_{name};")
        lines.append(f"VG_SCHEMA_STATIC_ASSERT(sizeof(VgSchema_{name}) == {desc['size']}, \"schema size {name}\");")
        for field in desc["fields"]:
            lines.append(f"VG_SCHEMA_STATIC_ASSERT(offsetof(VgSchema_{name}, {field['name']}) == {field['offset']}, \"schema offset {name}.{field['name']}\");")
    relocations = []
    def collect_relocations(type_name, base_offset, path):
        for field in schema["types"][type_name]["fields"]:
            field_layout = next(item for item in layouts[type_name]["fields"] if item["name"] == field["name"])
            field_offset = base_offset + field_layout["offset"]
            field_path = path + [field["name"]]
            if field.get("relocation"):
                relocations.append((field_path, field["relocation"], field_offset))
            elif field["type"] in schema["types"]:
                collect_relocations(field["type"], field_offset, field_path)
    collect_relocations(root, 0, [root])
    lines.append(f"#define VG_SCHEMA_{stem.upper()}_RELOCATION_COUNT {len(relocations)}u")
    for path, kind, offset in relocations:
        macro_path = "_".join(part.upper() for part in path[1:])
        lines.append(f"#define VG_SCHEMA_{stem.upper()}_RELOCATION_{macro_path}_KIND_{kind.upper()} 1u")
        lines.append(f"#define VG_SCHEMA_{stem.upper()}_RELOCATION_{macro_path}_OFFSET {offset}u")
    lines += ["#undef VG_SCHEMA_STATIC_ASSERT", "#endif"]
    out_dir.mkdir(parents=True, exist_ok=True)
    output = schema.get("output", "vg_task_root")
    (out_dir / f"{output}.h").write_text("\n".join(lines) + "\n", encoding="utf-8")
    reflection = {"schema": schema["schema"], "name": schema["name"], "version": schema["version"],
                  "schema_id": "sha256:" + hashlib.sha256(raw).hexdigest(), "layouts": layouts, "source_hash": "sha256:" + hashlib.sha256(raw).hexdigest()}
    reflection["relocations"] = [{"path": path, "kind": kind, "offset": offset}
                                 for path, kind, offset in relocations]
    (out_dir / f"{output}.reflection.json").write_text(json.dumps(reflection, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / f"{output}.layout.json").write_text(json.dumps({"schema_id": reflection["schema_id"], "root": root, "layout": layouts[root]}, indent=2, sort_keys=True) + "\n", encoding="utf-8")

def main():
    parser = argparse.ArgumentParser(); parser.add_argument("schema"); parser.add_argument("--out-dir", required=True)
    args = parser.parse_args(); source = Path(args.schema); emit(json.loads(source.read_text(encoding="utf-8")), Path(args.out_dir))

if __name__ == "__main__": main()
