# Explicit declarations, no source discovery and no implicit language upgrades.
function(vg_target name)
  set(fields SOURCES LINK_PRIVATE LINK_PUBLIC INCLUDE_PRIVATE INCLUDE_PUBLIC
    FEATURES_PRIVATE FEATURES_PUBLIC DEFINITIONS_PRIVATE DEFINITIONS_PUBLIC PROPERTIES DEPENDS)
  cmake_parse_arguments(PARSE_ARGV 1 row "" "TYPE" "${fields}")
  if(row_UNPARSED_ARGUMENTS OR row_KEYWORDS_MISSING_VALUES OR NOT row_SOURCES)
    message(FATAL_ERROR "Invalid target declaration: ${name}")
  endif()
  if(row_TYPE STREQUAL "EXECUTABLE")
    add_executable(${name} ${row_SOURCES})
  elseif(row_TYPE STREQUAL "STATIC")
    add_library(${name} STATIC ${row_SOURCES})
  else()
    message(FATAL_ERROR "Unknown target type for ${name}: ${row_TYPE}")
  endif()
  foreach(scope PRIVATE PUBLIC)
    if(row_LINK_${scope})
      target_link_libraries(${name} ${scope} ${row_LINK_${scope}})
    endif()
    if(row_INCLUDE_${scope})
      target_include_directories(${name} ${scope} ${row_INCLUDE_${scope}})
    endif()
    if(row_FEATURES_${scope})
      target_compile_features(${name} ${scope} ${row_FEATURES_${scope}})
    endif()
    if(row_DEFINITIONS_${scope})
      target_compile_definitions(${name} ${scope} ${row_DEFINITIONS_${scope}})
    endif()
  endforeach()
  if(row_PROPERTIES)
    set_target_properties(${name} PROPERTIES ${row_PROPERTIES})
  endif()
  if(row_DEPENDS)
    add_dependencies(${name} ${row_DEPENDS})
  endif()
endfunction()

function(vg_test name)
  if(TEST ${name})
    message(FATAL_ERROR "Duplicate test declaration: ${name}")
  endif()
  add_test(NAME ${name} ${ARGN})
endfunction()

function(vg_test_modes target prefix)
  foreach(mode IN LISTS ARGN)
    vg_test(${prefix}.${mode} COMMAND ${target} ${mode} ${CMAKE_CURRENT_SOURCE_DIR})
  endforeach()
endfunction()

function(vg_python_test name script)
  vg_test(${name} COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/${script} ${ARGN})
endfunction()

function(vg_schema input)
  set(outputs)
  foreach(name IN LISTS ARGN)
    list(APPEND outputs "${VG_GENERATED_DIR}/${name}")
  endforeach()
  if(NOT outputs)
    message(FATAL_ERROR "Schema declaration has no outputs: ${input}")
  endif()
  add_custom_command(OUTPUT ${outputs}
    COMMAND ${CMAKE_COMMAND} -E make_directory "${VG_GENERATED_DIR}"
    COMMAND ${Python3_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/tools/vg-schema/vg_schema.py"
      "${CMAKE_CURRENT_SOURCE_DIR}/${input}" --out-dir "${VG_GENERATED_DIR}"
    DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/${input}"
      "${CMAKE_CURRENT_SOURCE_DIR}/tools/vg-schema/vg_schema.py"
    VERBATIM)
  set_property(GLOBAL APPEND PROPERTY VG_SCHEMA_OUTPUTS ${outputs})
endfunction()
