/* generated by vg-schema; source-sha256: a8f7cd05b11f94b672c7da059b85a3895bfcf0413a50388e7b8e2044d27202f4 */
/* do not edit */
#ifndef VG_GENERATED_SCENEROOTRASTER_H
#define VG_GENERATED_SCENEROOTRASTER_H
#include <stdint.h>
#include <stddef.h>
#include <vg/vg.h>
#ifdef __cplusplus
#define VG_SCHEMA_STATIC_ASSERT(cond, msg) static_assert((cond), msg)
#else
#define VG_SCHEMA_STATIC_ASSERT(cond, msg) _Static_assert((cond), msg)
#endif
#define VG_SCHEMA_SCENEROOTRASTER_ID UINT64_C(0xa8f7cd05b11f94b6)
VG_SCHEMA_STATIC_ASSERT(sizeof(VgFacetRef) == 8, "public facet ref layout");
VG_SCHEMA_STATIC_ASSERT(offsetof(VgFacetRef, index) == 0, "public facet ref index offset");
VG_SCHEMA_STATIC_ASSERT(offsetof(VgFacetRef, generation) == 4, "public facet ref generation offset");
#define VG_SCHEMA_SCENEROOTRASTER_CONTRACT_NAME "vg.scene-root.raster/v1"
typedef struct VgSchema_Material {
  float base_color[4];
  VgFacetRef albedo;
} VgSchema_Material;
VG_SCHEMA_STATIC_ASSERT(sizeof(VgSchema_Material) == 24, "schema size Material");
VG_SCHEMA_STATIC_ASSERT(offsetof(VgSchema_Material, base_color) == 0, "schema offset Material.base_color");
VG_SCHEMA_STATIC_ASSERT(offsetof(VgSchema_Material, albedo) == 16, "schema offset Material.albedo");
typedef struct VgSchema_SceneRootRaster {
  float camera_clip_from_local[16];
  VgSchema_Material material;
} VgSchema_SceneRootRaster;
VG_SCHEMA_STATIC_ASSERT(sizeof(VgSchema_SceneRootRaster) == 88, "schema size SceneRootRaster");
VG_SCHEMA_STATIC_ASSERT(offsetof(VgSchema_SceneRootRaster, camera_clip_from_local) == 0, "schema offset SceneRootRaster.camera_clip_from_local");
VG_SCHEMA_STATIC_ASSERT(offsetof(VgSchema_SceneRootRaster, material) == 64, "schema offset SceneRootRaster.material");
#define VG_SCHEMA_SCENEROOTRASTER_ROOT_SIZE 88u
#define VG_SCHEMA_SCENEROOTRASTER_MATERIAL_SIZE 24u
#define VG_SCHEMA_SCENEROOTRASTER_MATERIAL_BASE_COLOR_OFFSET 0u
#define VG_SCHEMA_SCENEROOTRASTER_MATERIAL_ALBEDO_OFFSET 16u
#define VG_SCHEMA_SCENEROOTRASTER_SCENEROOTRASTER_SIZE 88u
#define VG_SCHEMA_SCENEROOTRASTER_SCENEROOTRASTER_CAMERA_CLIP_FROM_LOCAL_OFFSET 0u
#define VG_SCHEMA_SCENEROOTRASTER_SCENEROOTRASTER_MATERIAL_OFFSET 64u
#define VG_SCHEMA_SCENEROOTRASTER_RELOCATION_COUNT 1u
#define VG_SCHEMA_SCENEROOTRASTER_RELOCATION_MATERIAL_ALBEDO_KIND_FACET 1u
#define VG_SCHEMA_SCENEROOTRASTER_RELOCATION_MATERIAL_ALBEDO_OFFSET 80u
#undef VG_SCHEMA_STATIC_ASSERT
#endif
